---
title: "Proposta Ação de Extensão 2020"
subtitle: "Plataforma para Divulgação da Probabilidade e Estatística da UFRGS"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Título
Plataforma (Ambiente Web) para Divulgação da Probabilidade e Estatística da UFRGS.


# 2. Resumo / Descritores
Criação de uma plataforma para divulgação da Probabilidade e Estatística na era 
da ciência de dados a todos os interessados dentro e fora da Universidade. De 
forma colaborativa, além dos professores do Departamento de Estatística (Dest) 
poderão desenvolver conteúdos pesquisadores, estudantes e público em geral 
interessado em ciência de dados, tendo como foco a discussão de conceitos 
básicos em Probabilidade e Estatistica através do software R.


# 2. Descrição do objeto
O presente projeto tem por objetivo criar uma plataforma para divulgação da 
"Probabilidade e Estatistica" pelo Departamento de Estatística da UFRGS 
(Dest/UFGRS), além de ser um recurso educacional digital para também 
complementar o ensino de estatística na disciplina MAT02219 - Probabilidade 
e Estatística – modalidade ensino à distância (EAD).

A plataforma será criada em formato `HTML` com o auxílio do pacote `blogdown` 
(https://bookdown.org/yihui/blogdown/), do software estatístico `R` 
(https://www.r-project.org/). Ela incluirá conteúdos interativos como um livro 
com conceitos básicos e conteúdo atualizado, complementares aos abordados na 
disciplina MAT02219, um conjunto de atividades, vídeos e um `blog` para 
interação com os usuários. 

Nosso interesse ao complementar o conteúdo da disciplina MAT02219 é desenvolver 
assuntos relacionados à ciência de dados e como ela tem modificado a maneira de 
se pensar e fazer a probabilidade e a estatística. Principalmente, abordaremos 
como a computação se insere na prática estatística atualmente, também 
introduziremos conceitos básicos em computação/programação estatística.

Outro objetivo da plataforma é a divulgação do Departamento de Estatística e a 
promoção da área como uma poderosa ferramenta para resolução de problemas em 
análise de dados. Por ser um recurso disponível livremente na internet, o 
público se torna muito mais amplo do que os estudantes da disciplina MAT02219-EAD.
Além da disponibilização de conteúdos, o `blog` terá papel importante como 
espaço de discussões e divulgação de assuntos relacionados a probabilidade, a 
estatística para dentro e fora da Universidade.


# 3. Relevância
Colocar dados da disciplina...

O recurso digital poderá contribuir para qualificar o ensino de probabilidade e 
estatística em todas as esferas da Universidade, incluindo a extensão 
universitária, podendo também serem explorados temas direcionados à educação 
básica. Inicialmente utilizaremos a plataforma como complemento ao ensino de 
MAT02219 no que tange assuntos relacionados à implementação/computação/programação 
de métodos estatísticos no software `R`. O conteúdo produzido poderá também ser 
utilizado como base em cursos de extensao, por futuros estudantes da disciplina 
MAT02219, público em geral interessado em probabilidade, estatística e 
programação em `R`, atingindo dessa forma um público bastante amplo.

Disciplinas presenciais e à distância poderão se beneficiar do recurso. 
Introduzir atividades relacionadas a questões computacionais e programação 
no *software* `R` poderão ser realizadas online, sem a necessidade de instalação 
de qualquer *software*. A integração desse tipo de atividade com plataforma 
educacionais, como o moodle por exemplo, demandaria muito mais recursos.



# 4. Mapa de navegação, storyboard ou roteiro
A plataforma ficará hospedada no endereço https://www.ufrgs.br/probabilidade-estatistica/ 
e conterá módulos para cada uma das atividades abaixo:

a. **Livro digital** - criado com base no pacote `bookdown` (https://bookdown.org/), 
com conteúdo atualizado voltado à ciência de dados, trazendo uma introdução à 
programação em estatística utilizando o software `R`. Parte do livro já está 
concluída e sendo revisada (referencia a bolsa anterior).

b. **Atividades** - exercícios farão parte do livro e serão criados com o auxílio 
do pacote `exams`. Disponibilizaremos atividades para os usuários trabalharem questões 
conceituais, teoria e prática e computação em `R`. (mostrar algo que ja temos?)

c. **Vídeos e *podcasts* ** - assuntos gerais e conceitos básicos para 
complementação do conteúdo que já vem sendo desenvolvido para a disciplina 
MAT02219-EAD são temas para discussões. Resoluções de exercícios e conteúdos 
em formato `podcasts` também poderão fazer parte desse módulo do recurso. 
(colocar link com exemplos?)

d. ***Blog*** - o pacote `blogdown` permite a criação de páginas em formato 
`HTML` que incluem recursos para criação e edição de `posts` no formato de 
um `blog`. Com isso a plataforma abrirá um canal de interacao com o público. 
As postagens serão moderadas pela equipe de professores que estiverem 
encarregados das turmas de MAT02219-EAD e prioritariamente serão abordados 
temas que envolvam a probabilidade e a estatística na UFRGS.



# 5. Descrição dos recursos de interatividade
O usuário da plataforma 'Probabilidade e Estatística' navegará interativamente 
nas páginas do livro eletrônico e poderá resolver os exercícios propostos. 
Dúvidas e sugestões serão recebidas pela equipe mantedora da plataforma. Fóruns 
também poderão ser abertos para discussões sobre tópicos específicos. Por fim, 
dúvidas e discussões podem ser temas para vídeos e *podcasts*.

Além disso, uma maneira de interação com a comunidade em geral será o *blog* 
mantido na plataforma. Temas atuais ligados a ciência de dados e programação 
serão propostos à comunidade a fim de fomentar a reflexão sobre o impacto do 
uso da probabilidade e estatística na ciência e no nosso cotidiano.


# 6. Descrição da proposta de validação do Recurso Educacional Digital dentro do período de vigência deste edital
As etapas de desenvolvimento da plataforma são as seguintes:  
a. Desenvolvimento da página principal em formato `blogdown`: meses 1 a 4.  
b. Finalização do livro eletrônico no formato `bookdown`: meses 1 a 6.  
c. Documentação das funções, gravação de vídeos: meses 1 a 6.  
d. Disponibilização da plataforma: mês 6.  
e. Validação da plataforma: meses 6 a 11.

A validação da plataforma será feita por meio de pesquisa de usuários (alunos e professores) com turmas da disciplina Probabilidade e Estatística – modalidade EAD – no semestre 2020/2. Serão avaliados os aspectos de conteúdo da plataforma, layout, acessibilidade, facilidade do uso, entre outros. 


# 7. Inovação
O ensino de computação estatística utilizando o `R` têm sido cada vez mais 
incentivada em sala de aula porém ainda não existe um conteúdo que sirva como 
referência do Departamento do Estatística. Dessa forma a plataforma servirá 
para suprir essa demanda, principalmente na formação complementar dos estudantes 
de MAT02219-EAD.

Um aspecto importante que uma plataforma criada com base no *software* `R` é a 
facilidade para se desenvolver recursos de aprendizagem em programação no próprio 
`R`. O pacote `blogdown` possibilita a integração de diversos formatos de 
conteúdos em `HTML` e têm sido muito utilizado por cientistas de dados. 

Outra possibilidade de uso da plataforma será em cursos de extensão e MOOCs 
(*Massive Online Open Courses*). A extensão universitária como forma de cursos 
são muito comuns na Universidade e módulos específicos poderão ser criados 
conforme a demanda. Um escopo e cronograma devem ser definidos em cada 
proposta.



# 8. Apresentar plano e cronograma de atividades do bolsista 
Escrever tópicos a serem abordados...  


# 9. Referências




